(SETQ  ACADLSPASDOC  0)
(Command "netload" "C:\\Program Files\\Autodesk\\ApplicationPlugins\\RedBracketConnector.bundle\\Contents\\AutocadPlugIn.dll")
(Command "_Ribbon")
(Command "COMMANDLINE")
(Command "myribbon")